### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by warez1975** [dougiteixeira/proxmoxve#101]
Proxmox VE 2.0.2 on Home Assistant Core 2023.6.3

Error in Proxmox VE: Swap* Sensors are always unavailable in QEMU... Swap* Sensors works like a charm in the LXC 

This is my log error:

`Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 431, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 469, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/proxmoxve/sensor.py", line 564, in native_value
    native_value = value(data)
                   ^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/proxmoxve/sensor.py", line 403, in <lambda>
    value_fn=lambda x: (x.swap_free / x.swap_total) if x.swap_total > 0 else 0,
                                                       ^^^^^^^^^^^^
AttributeError: 'ProxmoxVMData' object has no attribute 'swap_total'`

Please can someone help me?

**Comment by dougiteixeira** [comment]
Proxmox VMs (QEMU) do not have SWAP, these sensors will be removed in the next release.
