### ISSUE TITLE
Failed to Setup

### ISSUE THREAD

**Issue by danielbelchior** [dougiteixeira/proxmoxve#206]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

I am trying to connect to my proxmox server, but I cant.
`
2024-01-01 18:19:04.774 ERROR (MainThread) [custom_components.proxmoxve] Error fetching proxmox_coordinator_disk_pve_/dev/sdc data: 500 Internal Server Error: Error getting S.M.A.R.T. data: Exit code: 1
2024-01-01 18:19:05.029 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.2:8006 for proxmoxve
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/__init__.py", line 484, in async_setup_entry
    for storage_id in config_entry.data[CONF_STORAGE]:
                      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'storage'
`
![Captura de tela 2024-01-01 182423](https://github.com/dougiteixeira/proxmoxve/assets/95664/c5e3cbca-2120-4833-9f74-15064715d642)


### In which version of Home Assistant Core do you have the problem?

2023.12.4

### What version of Proxmox VE Custom Integration has the issue?

3.2.2

### What version of Proxmox VE do you have the problem?

Linux 6.5.11-4-pve (2023-11-20T10:19Z)

### Diagnostics information

I cant download 
![Captura de tela 2024-01-01 182906](https://github.com/dougiteixeira/proxmoxve/assets/95664/a22b3683-0d50-4ee6-9d72-9fe0c36aea0d)


### Additional information

_No response_

**Comment by dougiteixeira** [comment]
I understand that you were using an automatically imported YAML configuration, correct?

I've included the fix for this in #225. It will be available in the next version.
