### ISSUE TITLE
'UndefinedType._singleton' (<enum 'UndefinedType'>)

### ISSUE THREAD

**Issue by Thomas55555** [dougiteixeira/proxmoxve#282]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

In the log files there is an error arround 5 times a day. For the other HD (sdb) it's around 10 times.
```
2024-03-18 18:20:27.241 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 668, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'UndefinedType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 261, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 417, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 497, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
    raise ValueError(
ValueError: Sensor sensor.disk_deskmini_dev_sda_temperature has device class 'temperature', state class 'measurement' unit '°C' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: 'UndefinedType._singleton' (<enum 'UndefinedType'>)
```

### In which version of Home Assistant Core do you have the problem?

2024.3.1

### What version of Proxmox VE Custom Integration has the issue?

3.4.1

### What version of Proxmox VE do you have the problem?

7.4-17

### Diagnostics information

[home-assistant_proxmoxve_2024-03-18T17-18-17.419Z.log](https://github.com/dougiteixeira/proxmoxve/files/14640169/home-assistant_proxmoxve_2024-03-18T17-18-17.419Z.log)

[proxmoxve-9abc6802b76079fbf53bbf1557a86c92-Disk deskmini__dev_sdb-f19bdf471d7b8b6069b51f6104326292.json](https://github.com/dougiteixeira/proxmoxve/files/14640172/proxmoxve-9abc6802b76079fbf53bbf1557a86c92-Disk.deskmini__dev_sdb-f19bdf471d7b8b6069b51f6104326292.json)

### Additional information

Thank you for this nice integration!!!!

**Comment by DNC74** [comment]
Same log errors are appearing on my installation. The only difference are the versions. I use
- Custom Integration 3.4.1 (same)
- Proxmox VE 8.1.5
- Home Assistant Core 2024.3.3

It happens for both nvme drives while reading temperature.

```
2024-03-24 18:00:38.782 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 668, in state
numerical_value = float(value) # type:ignore[arg-type]
^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'UndefinedType'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 261, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 417, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 497, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in __async_calculate_state
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
raise ValueError(
ValueError: Sensor sensor.disk_pve01_dev_nvme0n1_temperature has device class 'temperature', state class 'measurement' unit '°C' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: 'UndefinedType._singleton' (<enum 'UndefinedType'>)
```

```
2024-03-25 23:41:44.411 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 668, in state
numerical_value = float(value) # type:ignore[arg-type]
^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'UndefinedType'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 261, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 417, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 497, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in __async_calculate_state
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
raise ValueError(
ValueError: Sensor sensor.disk_pve01_dev_nvme1n1_temperature has device class 'temperature', state class 'measurement' unit '°C' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: 'UndefinedType._singleton' (<enum 'UndefinedType'>)
2024-03-25 23:42:54.787 ERROR (MainThread) [custom_components.proxmoxve] Error fetching proxmox_coordinator_disk_pve01_/dev/nvme1n1 data:
```

**Comment by Greminn** [comment]
Same issue here: 

Integration: 3.4.1
Proxmox: 8.2

Core 2024.5.1
Supervisor 2024.04.4
Operating System 12.2

2024-05-04 12:46:39.186 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 663, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'UndefinedType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 492, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1015, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 665, in state
    raise ValueError(
ValueError: Sensor sensor.node_pve_total_updates has device class 'None', state class 'measurement' unit 'None' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: 'UndefinedType._singleton' (<enum 'UndefinedType'>)
