### ISSUE TITLE
Cannot fetch all disks information due to non standard SMART information

### ISSUE THREAD

**Issue by mdabrow6** [dougiteixeira/proxmoxve#293]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Thank you for a great progress with this PVE custom integration.

My Proxmox VE custom integration doesn't show all disks in Home Assistant. Only sdb is visible, without sda due to non numeric information in SMART.

Error from log file:

```
2024-05-05 12:43:59.890 ERROR (MainThread) [custom_components.proxmoxve] Unexpected error fetching proxmox_coordinator_disk_pve-laptop_/dev/sda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/coordinator.py", line 706, in _async_update_data
    power_hours=int(disk_attributes["power_hours"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '2h+37m+13.600s'
```

Wrong SMART values for my KINGSTON disk, model SV300S37A480G:
Power_On_Hours - no such SMART record
Power_On_Hours_and_Msec - '2h+37m+13.600s'
Airflow_Temprerature_Cel - '35 (Min/Max 18/40)'
Temprerature_Celsius - '35 (Min/Max 18/40)'

![image](https://github.com/dougiteixeira/proxmoxve/assets/97689702/8e96f20b-7595-4bc4-83fc-914a3da3b823)

### In which version of Home Assistant Core do you have the problem?

2024.5.1

### What version of Proxmox VE Custom Integration has the issue?

3.4.1

### What version of Proxmox VE do you have the problem?

8.2.2

### Additional information

I found this issue as I'm preparing a new node with completly new SSD disks, new PVE, and new HASS.

**Comment by mdabrow6** [comment]
Works properly with the new version 3.4 2.
