### ISSUE TITLE
Cannot add or remove containers at later date

### ISSUE THREAD

**Issue by marc115uk** [dougiteixeira/proxmoxve#312]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

I have this set up, have deleted a container in proxmox. I am getting a warning in settings saying the container does not exist. When I try to configure, add or remove nodes, I untick the container then every time I try to save it says unknown error has occurred. 

### In which version of Home Assistant Core do you have the problem?

2024.5.5

### What version of Proxmox VE Custom Integration has the issue?

3.4.2

### What version of Proxmox VE do you have the problem?

8.2.2

**Comment by dougiteixeira** [comment]
Please attach the log file: 

You can follow the steps below:

* [Enable integration debugging](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging).
* Reload the integration configuration entry.
[Download a diagnostic file](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics).
* [Disable integration debugging and download the generated log file](https://www.home-assistant.io/docs/configuration/troubleshooting/#disable-debug-logging-and-download-logs).
* Attach the diagnostic file and the generated log file here.

**Comment by ice413** [comment]
> Have the same problem as OP, but rolled back to 3.4.1 and removed the LXC without issues.

I had to rollback to 3.4.1 as well.
Something here that fail:
"File "/config/custom_components/proxmoxve/config_flow.py", line 438, in async_process_selection_changes"

**Comment by jeremysherriff** [comment]
Same issue here, have the needed logs been provided?

**Comment by forsethc** [comment]
I am seeing this issue as well.  

Same root cause, same behavior as described in the initial report

Here's the stack trace from my logs:

```
2024-06-03 18:37:47.665 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/proxmoxve/diagnostics.py", line 120, in async_get_api_data_diagnostics
    nodes[node["node"]]["storage"] = await hass.async_add_executor_job(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/api.py", line 82, in get_api
    api_result = proxmox.get(api_path)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/proxmoxer/core.py", line 169, in get
    return self(args)._request("GET", params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/proxmoxer/core.py", line 149, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 595 Errors during connection establishment, proxy handshake: No route to host - {'errors': b''}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp_session/__init__.py", line 199, in factory
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 295, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 256, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/diagnostics.py", line 205, in async_get_config_entry_diagnostics
    api_data = await async_get_api_data_diagnostics(hass, config_entry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/diagnostics.py", line 129, in async_get_api_data_diagnostics
    nodes[node["node"]]["storage"]["error"] = error
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'storage'
```

**Comment by HybridRCG** [comment]
Same issue as OP. Cannot add/remove VM's (QEMU) though.. with unknown error. 
I can however add/remove nodes from LXC's

**Comment by mukundv** [comment]
Same issue here too. Rolling back to 3.4.1 fixes the issue. 
Updated to 3.4.2 after removing the LXC

**Comment by aheath70** [comment]
Same problem here when trying to remove some old storage that no longer exists in my Proxmox Environment. Rolled back to 3.4.1 and was able to reconfigure, and then upgraded to 3.4.2.
