### ISSUE TITLE
runtime error message

### ISSUE THREAD

**Issue by brian316** [dougiteixeira/proxmoxve#316]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

the integration seems to work on boot but get this error in the logs.

# Logs
```
homeassistant      | 2024-05-28 09:21:08.628 ERROR (MainThread) [custom_components.proxmoxve] Unexpected error fetching proxmox_coordinator_update_pve data
homeassistant      | Traceback (most recent call last):
homeassistant      |   File "/config/custom_components/proxmoxve/coordinator.py", line 800, in poll_api
homeassistant      |     return get_api(proxmox, api_path)
homeassistant      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant      |   File "/config/custom_components/proxmoxve/api.py", line 82, in get_api
homeassistant      |     api_result = proxmox.get(api_path)
homeassistant      |                  ^^^^^^^^^^^^^^^^^^^^^
homeassistant      |   File "/usr/local/lib/python3.12/site-packages/proxmoxer/core.py", line 169, in get
homeassistant      |     return self(args)._request("GET", params=params)
homeassistant      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant      |   File "/usr/local/lib/python3.12/site-packages/proxmoxer/core.py", line 149, in _request
homeassistant      |     raise ResourceException(
homeassistant      | proxmoxer.core.ResourceException: 403 Forbidden: Permission check failed (/nodes/pve, Sys.Modify)
homeassistant      | 
homeassistant      | During handling of the above exception, another exception occurred:
homeassistant      | 
homeassistant      | Traceback (most recent call last):
homeassistant      |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
homeassistant      |     self.data = await self._async_update_data()
homeassistant      |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant      |   File "/config/custom_components/proxmoxve/coordinator.py", line 494, in _async_update_data
homeassistant      |     api_status = await self.hass.async_add_executor_job(
homeassistant      |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant      |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
homeassistant      |     result = self.fn(*self.args, **self.kwargs)
homeassistant      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant      |   File "/config/custom_components/proxmoxve/coordinator.py", line 814, in poll_api
homeassistant      |     async_create_issue(
homeassistant      |   File "/usr/src/homeassistant/homeassistant/helpers/issue_registry.py", line 311, in async_create_issue
homeassistant      |     issue_registry.async_get_or_create(
homeassistant      |   File "/usr/src/homeassistant/homeassistant/helpers/issue_registry.py", line 155, in async_get_or_create
homeassistant      |     self.hass.bus.async_fire(
homeassistant      |   File "/usr/src/homeassistant/homeassistant/core.py", line 1508, in async_fire
homeassistant      |     self._hass.verify_event_loop_thread("async_fire")
homeassistant      |   File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
homeassistant      |     frame.report(
homeassistant      |   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
homeassistant      |     _report_integration(what, integration_frame, level, error_if_integration)
homeassistant      |   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
homeassistant      |     raise RuntimeError(
homeassistant      | RuntimeError: Detected that custom integration 'proxmoxve' calls async_fire from a thread at custom_components/proxmoxve/coordinator.py, line 814: async_create_issue(. Please report it to the author of the 'proxmoxve' custom integration.
```

### In which version of Home Assistant Core do you have the problem?

latest

### What version of Proxmox VE Custom Integration has the issue?

latest

### What version of Proxmox VE do you have the problem?

latest

**Comment by dougiteixeira** [comment]
Fixes in #323
