### ISSUE TITLE
Add on won't start after update to HA 2024.12.4

### ISSUE THREAD

**Issue by rjing001** [dougiteixeira/proxmoxve#413]
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

After updating to HA 2024.12.4, this integration fails to set up.

### In which version of Home Assistant Core do you have the problem?

2024.12.4

### What version of Proxmox VE Custom Integration has the issue?

3.5.2

### What version of Proxmox VE do you have the problem?

7.4

### Logs file

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 8:22:20 AM (8 occurrences)
Last logged: 8:49:22 AM

Error setting up entry 192.168.1.139:8006 for proxmoxve
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/proxmoxve/__init__.py", line 349, in async_setup_entry
    token_name = entry_data[CONF_TOKEN_NAME]
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'token_name'

### Diagnostics file

No Option for diagnostic file from dropdown.

### Additional information

_No response_

**Comment by rjing001** [comment]
Issue can be closed, found solution here:
https://github.com/dougiteixeira/proxmoxve/issues/363#issuecomment-2506657664
